/// <reference types="astro/client" />

// worker-configuration.d.ts (generated by `wrangler types`) defines global `Env`.
// This re-exports it so `import { env } from "cloudflare:workers"` is typed.
declare module "cloudflare:workers" {
  const env: Env;
  export { env };
}

declare namespace App {
  interface Locals {
    isAdmin: boolean;
  }
}
